### ISSUE TITLE
Add store function

### ISSUE THREAD

**Issue by palash25** [palash25/CoWaPS#6]
Add a function to store data in csv format.

**Comment by sibasish14** [comment]
I would like to work on this issue.
Do I have install **requests** & **BeautifulSoup** ?

**Comment by sibasish14** [comment]
If yes, do I have to install it the same directory where I cloned CoWaPS?

**Comment by palash25** [comment]
No, you can do a system-wide installation using `pip` or its best to install anaconda on your system it comes with all important python packages.

**Comment by sibasish14** [comment]
Isn't request a part of python?
Never mind - installed it!
